# Header
logo_text: Legacy Posts - Explore. Dream. Discover.
menu:
  Home: /
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
